#!/bin/zsh

alias cd="HOME=~/mesosphere cd"
alias git=hub
alias securetether='sudo pppd user Default password 1 call securetether /dev/tty.Niartenyaw-SecureTether'

alias sl="ls"
function ls {
  /bin/ls -lhGFA "$@"
}
alias irb="pry"
alias be="bundle exec"
alias g="git status"

## General

## Ruby
alias rreset='be rails db:drop db:create db:migrate'

## Git
alias gaa='git add .'
alias gcm='git commit -m'
alias gcount='git rev-list --all --count'
alias gitgraph='git log --graph --decorate --oneline'

## Rails
alias rmodel='rails g model'
alias rcont='rails g controller'
alias rtest='be rails db:migrate db:test:load'
alias rmig='be rails db:migrate'


alias k='kubectl'
