set runtimepath+=~/.vim

source ~/.vim/vimrcs/basic.vim
source ~/.vim/vimrcs/filetypes.vim
source ~/.vim/vimrcs/plugins_config.vim
source ~/.vim/vimrcs/extended.vim

try
source ~/.vim/my_configs.vim
catch
endtry

colorscheme solarized

""""""""""""""""""
" Custom NERDTree config
" Change nerdtree toggle
map <C-n> :NERDTreeToggle<cr>
" Show dotfiles
let NERDTreeShowHidden=1
" Start NERDTree if no file specified when opening vim
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" open/close nodes with 'f'
let NERDTreeMapActivateNode='f'
" Custom NERDTree config
set wildignore+=*/node_modules/*,*.swp

""""""""""""""""""
" Goyo Zenmode configuration
function! s:goyo_enter()
  set number
  if exists("&relativenumber")
    set relativenumber
    au BufReadPost * set relativenumber
  endif
endfunction

""""""""""""""""""
" LimeLight configuration
let g:limelight_paragraph_span = 1
let g:limelight_priority = -1
let g:limelight_default_coefficient = 0.7
" autocmd! User GoyoEnter Limelight
" autocmd! User GoyoLeave Limelight!

"""""""""""""""""
" Ale
let g:ale_linters = {'ruby': ['standardrb']}
let g:ale_fixers = {'ruby': ['standardrb']}
let g:ale_fix_on_save = 1

"""""""""""""""""
" Go
filetype plugin indent on

" fzf plugin
set rtp+=/usr/local/opt/fzf
nnoremap <leader>f :Files<cr>
nnoremap <leader>a :Ag<cr>
nnoremap <leader>b :Buffers<cr>
nnoremap <leader>t :Tags <c-r><c-w><cr>
nnoremap <leader>bt :BTags<cr>

" [Tags] Command to generate tags file
let g:fzf_tags_command = 'ctags -R'

""""""""""""""""""
" General Custom config
" Set tabs to spaces and size 2
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Set relative line number at cursor
set number
if exists("&relativenumber")
  set relativenumber
  au BufReadPost * set relativenumber
endif

" Jbuilder highlighting
au BufNewFile,BufFilePre,BufRead *.json.jbuilder set ft=ruby

" Set max char column
set colorcolumn=80
hi ColorColumn ctermbg=238

" Scroll the viewport faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Do not fold by default
set nofoldenable

let g:vim_markdown_frontmatter = 1
